# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Copy together artifacts
        shell: bash
        run: |
          mkdir dist
          cp fabric/build/libs/*.jar dist
          cp forge/build/libs/*.jar dist
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          if-no-files-found: error
          path: dist/*
          
